[package]
name = "astroport-on-osmosis"
version = "1.0.1"
authors = ["Astroport"]
edition = "2021"
description = "External API of Astroport contracts on Osmosis"
license = "Apache-2.0"

[dependencies]
cosmwasm-schema = "1"
cosmwasm-std = "1"
astroport = { workspace = true }
